### ISSUE TITLE
Single quotes aren't escaped in PartiQL statements

### ISSUE THREAD

**Issue by knovichikhin** [amzn/smoke-dynamodb#68]
Noticed during testing that DynamoDB rejected malformed request. However, only the items that contained a single quote were affected. Upon further investigation, it turned out that PartiQL statement need to escape single quotes within strings.

The affected operations are the `monomophicBulkWrite` and `deleteItems` (both for keys and for existing items).

I'll submit a PR for this.

**Comment by haotianzhu** [comment]
Are the callers supposed to include the "\" in the statement?

**Comment by knovichikhin** [comment]
> Are the callers supposed to include the " \ " in the statement?

Single quotes in PartiQL statements are escaped with another single quote.
