### ISSUE TITLE
After transactionCanceled, transactWrite in InMemoryDynamoDBCompositePrimaryKeyTable wont clean inserted entries

### ISSUE THREAD

**Issue by haotianzhu** [amzn/smoke-dynamodb#89]
For dynamodb smoke 3.9.1 InMemoryDynamoDBCompositePrimaryKeyTable’s transactWrite wont remove inserted items.

https://github.com/amzn/smoke-dynamodb/blob/15a1600b74703de16ae1b75e890d9f425df8b0ec/Sources/SmokeDynamoDB/InMemoryDynamoDBCompositePrimaryKeyTable.swift#L184-L186

**Comment by tachyonics** [comment]
Resolving as this was released with [3.10.1](https://github.com/amzn/smoke-dynamodb/tree/3.10.1)
